### PR TITLE
Created the fourth H1 tag and added border radius to the styling

### PR DESCRIPTION
**Pull request by babucarr32**
I added a third H1 tag, with border radius.

### CODE REVIEW

**Review by Babu-carr — COMMENTED** [review]
Your changes cannot be accepted at the moment

**Comment by babucarr32** [comment]
Why?

**Review by Babu-carr — CHANGES_REQUESTED** [review]
The color should be changed to green instead of brown.

**Review by Babu-carr — APPROVED** [review]
Great changes. Now I can merge.

**Pull request merged**
